### PR TITLE
Refactoring and fixing bugs in the sdhc driver

### PR DESCRIPTION
**Pull request by skwasniak**
When we tried to use sdhc drive we have encountered several issues with it which we want to address in the PR.

Furthermore, following the boy scout rule, we've also cleaned up some minor things. 

Looking forward to your feedback.

Cheers!

### CODE REVIEW

**Comment by axel-h** [comment]
@ssrg-bamboo `test`

**Comment by ssrg-bamboo** [comment]
Hello, I'm a bot! I'll bring this PR into Trustworthy Systems and run some tests

**Comment by skwasniak** [comment]
@ssrg-bamboo test

**Comment by skwasniak** [comment]
@ssrg-bamboo `test`

**Comment by skwasniak** [comment]
@ssrg-bamboo "test"

**Comment by skwasniak** [comment]
@ssrg-bamboo 'test'

**Comment by skwasniak** [comment]
@ssrg-bamboo `test`

**Comment by axel-h** [comment]
@ssrg-bamboo `test`

**Comment by ssrg-bamboo** [comment]
Hello, I'm a bot! I'll bring this PR into Trustworthy Systems and run some tests

**Comment by ssrg-bamboo** [comment]
## Test results for commit a1f2252d1facd7b0fef6d59ae885d443d49434ce

### Summary

#### NOTE: some test results have been updated!

| Test name | Result |
| --- | --- |
| Code Quality - Check licenses - projects_libs - EXT-Hensoldt-Cyber-SEOS-1663-5 | SUCCESSFUL |
| Code Quality - Style - projects_libs - EXT-Hensoldt-Cyber-SEOS-1663-5 | FAILED |

### Detailed failure logs

| Project | Stage | Result summary |
| --- | --- | --- |
| Code Quality - Style - projects_libs - EXT-Hensoldt-Cyber-SEOS-1663-5 | Style check on changed files | 1 of 3 jobs failed |

**Job: gitlint**
Build logs

    07-Oct-2020 23:45:02	Build Code Quality - Style - projects_libs - EXT-Hensoldt-Cyber-SEOS-1663-5 - gitlint #2 (CQ-PROJECTSLIBSSTYLE22-PROJECTSLIBSGITLINTPR-2) started building on agent A local agent 1
    07-Oct-2020 23:45:02	I run on the Bamboo server!
    07-Oct-2020 23:45:02	Build working directory is /var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-PROJECTSLIBSSTYLE22-PROJECTSLIBSGITLINTPR
    07-Oct-2020 23:45:02	Executing build Code Quality - Style - projects_libs - EXT-Hensoldt-Cyber-SEOS-1663-5 - gitlint #2 (CQ-PROJECTSLIBSSTYLE22-PROJECTSLIBSGITLINTPR-2)
    07-Oct-2020 23:45:02	Preparing artifact 'code' for use at /var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-PROJECTSLIBSSTYLE22-PROJECTSLIBSGITLINTPR/. (location: .)
    07-Oct-2020 23:45:02	Artifact 'code' prepared in 31.96 ms at /var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-PROJECTSLIBSSTYLE22-PROJECTSLIBSGITLINTPR/./code.tar.gz
    07-Oct-2020 23:45:02	Running pre-build action: VCS Version Collector
    07-Oct-2020 23:45:02	Starting task 'Untar code' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    07-Oct-2020 23:45:02	+ tar xf code.tar.gz --recursive-unlink
    07-Oct-2020 23:45:02	Finished task 'Untar code' with result: Success
    07-Oct-2020 23:45:02	Starting task 'Set permissions so Bamboo can cleanup' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    07-Oct-2020 23:45:02	+ chmod -R o+rwx /var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-PROJECTSLIBSSTYLE22-PROJECTSLIBSGITLINTPR
    07-Oct-2020 23:45:03	Finished task 'Set permissions so Bamboo can cleanup' with result: Success
    07-Oct-2020 23:45:03	Starting task 'Lint commit messages' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    07-Oct-2020 23:45:03	+ cd projects_libs
    07-Oct-2020 23:45:03	+ '[' -f .gitlint ']'
    07-Oct-2020 23:45:03	+ CONFIG=/var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-PROJECTSLIBSSTYLE22-PROJECTSLIBSGITLINTPR/seL4_tools/misc/.gitlint
    07-Oct-2020 23:45:03	+ gitlint --commits 947fa8e1723948f2792df33dcd3c43b15aca6296..a1f2252d1facd7b0fef6d59ae885d443d49434ce --config /var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-PROJECTSLIBSSTYLE22-PROJECTSLIBSGITLINTPR/seL4_tools/misc/.gitlint
    07-Oct-2020 23:45:36	Commit a1f2252d1f:
    07-Oct-2020 23:45:36	3: B6 Body message is missing
    07-Oct-2020 23:45:36	
    07-Oct-2020 23:45:36	Commit d470133034:
    07-Oct-2020 23:45:36	3: B1 Line exceeds max length (79>72): "To improve readability and to avoid future errors CSD version is now abstracted"
    07-Oct-2020 23:45:36	
    07-Oct-2020 23:45:36	Commit 588610cbfd:
    07-Oct-2020 23:45:36	3: B1 Line exceeds max length (76>72): "mmc_card_capacity will now return signed value due to the following reasons:"
    07-Oct-2020 23:45:36	7: B1 Line exceeds max length (73>72): "2. Signed 64 bit value is enough for holding the theoretical SD card size"
    07-Oct-2020 23:45:36	8: B1 Line exceeds max length (73>72): "   of 8 EiB (2^63 = 2^3 * 2^60 = 2^3 * 1024 ^ 6) what is more than enough"
    07-Oct-2020 23:45:36	
    07-Oct-2020 23:45:36	Commit 3e9ada2916:
    07-Oct-2020 23:45:36	1: T1 Title exceeds max length (53>50): "libsdhcdrivers: Enable reading Present State Register"
    07-Oct-2020 23:45:36	
    07-Oct-2020 23:45:36	Commit 8301eb25a7:
    07-Oct-2020 23:45:36	1: T1 Title exceeds max length (54>50): "libsdhcdrivers: Free allocated memory before returning"
    07-Oct-2020 23:45:36	3: B6 Body message is missing
    07-Oct-2020 23:45:36	
    07-Oct-2020 23:45:36	Commit b833480f3e:
    07-Oct-2020 23:45:36	1: T1 Title exceeds max length (60>50): "libsdhcdrivers: Allow for usage with standard capacity cards"
    07-Oct-2020 23:45:36	Failing task since return code of [/var/atlassian/application-data/bamboo/temp/CQ-PROJECTSLIBSSTYLE22-PROJECTSLIBSGITLINTPR-2-ScriptBuildTask-1274245495639666907.sh] was 9 while expected 0
    07-Oct-2020 23:45:36	Finished task 'Lint commit messages' with result: Failed
    07-Oct-2020 23:45:36	Starting task 'Set permissions so Bamboo can cleanup' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    07-Oct-2020 23:45:36	+ chmod -R o+rwx /var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-PROJECTSLIBSSTYLE22-PROJECTSLIBSGITLINTPR
    07-Oct-2020 23:45:36	Finished task 'Set permissions so Bamboo can cleanup' with result: Success
    07-Oct-2020 23:45:36	Running post build plugin 'NCover Results Collector'
    07-Oct-2020 23:45:36	Running post build plugin 'Artifact Copier'
    07-Oct-2020 23:45:36	Running post build plugin 'npm Cache Cleanup'
    07-Oct-2020 23:45:36	Running post build plugin 'Clover Results Collector'
    07-Oct-2020 23:45:36	Running post build plugin 'Docker Container Cleanup'
    07-Oct-2020 23:45:36	Successfully removed working directory at '/var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-PROJECTSLIBSSTYLE22-PROJECTSLIBSGITLINTPR'
    07-Oct-2020 23:45:36	Finalising the build...
    07-Oct-2020 23:45:36	Stopping timer.
    07-Oct-2020 23:45:36	Build CQ-PROJECTSLIBSSTYLE22-PROJECTSLIBSGITLINTPR-2 completed.
    07-Oct-2020 23:45:36	Running on server: post build plugin 'NCover Results Collector'
    07-Oct-2020 23:45:36	Running on server: post build plugin 'Build Hanging Detection Configuration'
    07-Oct-2020 23:45:36	Running on server: post build plugin 'Clover Delta Calculator'
    07-Oct-2020 23:45:36	Running on server: post build plugin 'Maven Dependencies Postprocessor'
    07-Oct-2020 23:45:36	All post build plugins have finished
    07-Oct-2020 23:45:36	Generating build results summary...
    07-Oct-2020 23:45:36	Saving build results to disk...
    07-Oct-2020 23:45:36	Store variable context...
    07-Oct-2020 23:45:36	Indexing build results...
    07-Oct-2020 23:45:36	Finished building CQ-PROJECTSLIBSSTYLE22-PROJECTSLIBSGITLINTPR-2.


This is the most I can report on right now, sorry!

**Comment by abrandnewusername** [comment]
@ssrg-bamboo `test`

**Comment by ssrg-bamboo** [comment]
Hello, I'm a bot! I'll bring this PR into Trustworthy Systems and run some tests

**Comment by ssrg-bamboo** [comment]
All the tests we ran have passed! Nice job!

**Comment by skwasniak** [comment]
The https://sel4.systems/pipermail/devel/2017-February/001286.html should address with the commit `libsdhcdrivers: Actively initialize bus width`.

**Comment by xurtis** [comment]
Merged internally, should see changes propagate to here once another round of tests pass.

**Pull request merged**
